version: "2"

services:
  socialdevops-db:
    image: postgres
    container_name: "socialdevops-db"
    volumes:
      - "socialdevops_db:/var/lib/postgresql/data"
    environment:
      - POSTGRES_PASSWORD=$PGPASSWORD
      - POSTGRES_USER=$PGUSER
      - POSTGRES_DB=$PGDATABASE
    ports:
      - "5432:5432"

volumes:
  socialdevops_db:
    external: true
