name:                socialdevops
version:             0.1.0.0
github:              "githubuser/socialdevops"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/socialdevops#README.md>

dependencies:
# base
- base >= 4.7 && < 5
# data
- bytestring
- time
- text
- case-insensitive
- uuid
- uuid-types
- binary
- aeson
- data-default
# control
- transformers
- lens
# HTTP
- http-types
- servant
- servant-server
- wai
- warp
- wai-extra
- streaming-commons
# API specs
- swagger2
- servant-swagger
# logging
- wai-logger
- fast-logger
- opentelemetry == 0.6.1
- opentelemetry-wai == 0.6.1
# DB
- beam-core
- beam-postgres
- beam-migrate
- postgresql-simple

library:
  source-dirs:
    - src
    - src/resources
    - src/repositories
    - src/models

executables:
  socialdevops-exe:
    main:                Main.hs
    source-dirs:
    - app
    - src
    - src/resources
    - src/repositories
    - src/models
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - socialdevops

tests:
  socialdevops-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - socialdevops
    - hspec
    - hspec-wai
    - hspec-wai-json
    - aeson
